# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros2_action.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/ros2_action.proto\x12\x1fviamlabs.service.ros2_action.v1\x1a\x1cgoogle/api/annotations.proto\";\n\rActionRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n\x06\x61\x63tion\x18\x02 \x01(\tR\x06\x61\x63tion\",\n\x0e\x41\x63tionResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\xae\x04\n\x11ROS2ActionService\x12\xb2\x01\n\x08SendGoal\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"E\x82\xd3\xe4\x93\x02?\"=/viamsoleng/api/v1/service/ros2_action/{name}/send_goal_async\x12\xb0\x01\n\nCancelGoal\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"A\x82\xd3\xe4\x93\x02;\"9/viamsoleng/api/v1/service/ros2_action/{name}/cancel_goal\x12\xb0\x01\n\nGoalStatus\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"A\x82\xd3\xe4\x93\x02;\"9/viamsoleng/api/v1/service/ros2_action/{name}/goal_statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ros2_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['SendGoal']._loaded_options = None
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['SendGoal']._serialized_options = b'\202\323\344\223\002?\"=/viamsoleng/api/v1/service/ros2_action/{name}/send_goal_async'
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['CancelGoal']._loaded_options = None
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['CancelGoal']._serialized_options = b'\202\323\344\223\002;\"9/viamsoleng/api/v1/service/ros2_action/{name}/cancel_goal'
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['GoalStatus']._loaded_options = None
  _globals['_ROS2ACTIONSERVICE'].methods_by_name['GoalStatus']._serialized_options = b'\202\323\344\223\002;\"9/viamsoleng/api/v1/service/ros2_action/{name}/goal_status'
  _globals['_ACTIONREQUEST']._serialized_start=90
  _globals['_ACTIONREQUEST']._serialized_end=149
  _globals['_ACTIONRESPONSE']._serialized_start=151
  _globals['_ACTIONRESPONSE']._serialized_end=195
  _globals['_ROS2ACTIONSERVICE']._serialized_start=198
  _globals['_ROS2ACTIONSERVICE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
