# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/ros2_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.ros2_service_pb2


class ROS2ServiceServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Call(self, stream: 'grpclib.server.Stream[proto.ros2_service_pb2.ServiceRequest, proto.ros2_service_pb2.ServiceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Destroy(self, stream: 'grpclib.server.Stream[proto.ros2_service_pb2.ServiceRequest, proto.ros2_service_pb2.ServiceResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Status(self, stream: 'grpclib.server.Stream[proto.ros2_service_pb2.ServiceRequest, proto.ros2_service_pb2.ServiceResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Call': grpclib.const.Handler(
                self.Call,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_service_pb2.ServiceRequest,
                proto.ros2_service_pb2.ServiceResponse,
            ),
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Destroy': grpclib.const.Handler(
                self.Destroy,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_service_pb2.ServiceRequest,
                proto.ros2_service_pb2.ServiceResponse,
            ),
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Status': grpclib.const.Handler(
                self.Status,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_service_pb2.ServiceRequest,
                proto.ros2_service_pb2.ServiceResponse,
            ),
        }


class ROS2ServiceServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Call = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Call',
            proto.ros2_service_pb2.ServiceRequest,
            proto.ros2_service_pb2.ServiceResponse,
        )
        self.Destroy = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Destroy',
            proto.ros2_service_pb2.ServiceRequest,
            proto.ros2_service_pb2.ServiceResponse,
        )
        self.Status = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_service.v1.ROS2ServiceService/Status',
            proto.ros2_service_pb2.ServiceRequest,
            proto.ros2_service_pb2.ServiceResponse,
        )
