# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/ros2_action.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.ros2_action_pb2


class ROS2ActionServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SendGoal(self, stream: 'grpclib.server.Stream[proto.ros2_action_pb2.ActionRequest, proto.ros2_action_pb2.ActionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CancelGoal(self, stream: 'grpclib.server.Stream[proto.ros2_action_pb2.ActionRequest, proto.ros2_action_pb2.ActionResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GoalStatus(self, stream: 'grpclib.server.Stream[proto.ros2_action_pb2.ActionRequest, proto.ros2_action_pb2.ActionResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/SendGoal': grpclib.const.Handler(
                self.SendGoal,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_action_pb2.ActionRequest,
                proto.ros2_action_pb2.ActionResponse,
            ),
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/CancelGoal': grpclib.const.Handler(
                self.CancelGoal,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_action_pb2.ActionRequest,
                proto.ros2_action_pb2.ActionResponse,
            ),
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/GoalStatus': grpclib.const.Handler(
                self.GoalStatus,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros2_action_pb2.ActionRequest,
                proto.ros2_action_pb2.ActionResponse,
            ),
        }


class ROS2ActionServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SendGoal = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/SendGoal',
            proto.ros2_action_pb2.ActionRequest,
            proto.ros2_action_pb2.ActionResponse,
        )
        self.CancelGoal = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/CancelGoal',
            proto.ros2_action_pb2.ActionRequest,
            proto.ros2_action_pb2.ActionResponse,
        )
        self.GoalStatus = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros2_action.v1.ROS2ActionService/GoalStatus',
            proto.ros2_action_pb2.ActionRequest,
            proto.ros2_action_pb2.ActionResponse,
        )
