# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros2_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ros2_service.proto',
  package='viamlabs.service.ros2_service.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18proto/ros2_service.proto\x12 viamlabs.service.ros2_service.v1\x1a\x1cgoogle/api/annotations.proto\">\n\x0eServiceRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\"-\n\x0fServiceResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\x9f\x04\n\x12ROS2ServiceService\x12\xa8\x01\n\x04\x43\x61ll\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\";\x82\xd3\xe4\x93\x02\x35\"3/viamsoleng/api/v1/service/ros2_service/{name}/call\x12\xae\x01\n\x07\x44\x65stroy\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\">\x82\xd3\xe4\x93\x02\x38\"6/viamsoleng/api/v1/service/ros2_service/{name}/destroy\x12\xac\x01\n\x06Status\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\"=\x82\xd3\xe4\x93\x02\x37\"5/viamsoleng/api/v1/service/ros2_service/{name}/statusb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_SERVICEREQUEST = _descriptor.Descriptor(
  name='ServiceRequest',
  full_name='viamlabs.service.ros2_service.v1.ServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='viamlabs.service.ros2_service.v1.ServiceRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='viamlabs.service.ros2_service.v1.ServiceRequest.service', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='service', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=154,
)


_SERVICERESPONSE = _descriptor.Descriptor(
  name='ServiceResponse',
  full_name='viamlabs.service.ros2_service.v1.ServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='viamlabs.service.ros2_service.v1.ServiceResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='response', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['ServiceRequest'] = _SERVICEREQUEST
DESCRIPTOR.message_types_by_name['ServiceResponse'] = _SERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceRequest = _reflection.GeneratedProtocolMessageType('ServiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEREQUEST,
  '__module__' : 'proto.ros2_service_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_service.v1.ServiceRequest)
  })
_sym_db.RegisterMessage(ServiceRequest)

ServiceResponse = _reflection.GeneratedProtocolMessageType('ServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVICERESPONSE,
  '__module__' : 'proto.ros2_service_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_service.v1.ServiceResponse)
  })
_sym_db.RegisterMessage(ServiceResponse)



_ROS2SERVICESERVICE = _descriptor.ServiceDescriptor(
  name='ROS2ServiceService',
  full_name='viamlabs.service.ros2_service.v1.ROS2ServiceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=204,
  serialized_end=747,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='viamlabs.service.ros2_service.v1.ROS2ServiceService.Call',
    index=0,
    containing_service=None,
    input_type=_SERVICEREQUEST,
    output_type=_SERVICERESPONSE,
    serialized_options=b'\202\323\344\223\0025\"3/viamsoleng/api/v1/service/ros2_service/{name}/call',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='viamlabs.service.ros2_service.v1.ROS2ServiceService.Destroy',
    index=1,
    containing_service=None,
    input_type=_SERVICEREQUEST,
    output_type=_SERVICERESPONSE,
    serialized_options=b'\202\323\344\223\0028\"6/viamsoleng/api/v1/service/ros2_service/{name}/destroy',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='viamlabs.service.ros2_service.v1.ROS2ServiceService.Status',
    index=2,
    containing_service=None,
    input_type=_SERVICEREQUEST,
    output_type=_SERVICERESPONSE,
    serialized_options=b'\202\323\344\223\0027\"5/viamsoleng/api/v1/service/ros2_service/{name}/status',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROS2SERVICESERVICE)

DESCRIPTOR.services_by_name['ROS2ServiceService'] = _ROS2SERVICESERVICE

# @@protoc_insertion_point(module_scope)
