# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros2_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/ros2_service.proto\x12 viamlabs.service.ros2_service.v1\x1a\x1cgoogle/api/annotations.proto\">\n\x0eServiceRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07service\x18\x02 \x01(\tR\x07service\"-\n\x0fServiceResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\x9f\x04\n\x12ROS2ServiceService\x12\xa8\x01\n\x04\x43\x61ll\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\";\x82\xd3\xe4\x93\x02\x35\"3/viamsoleng/api/v1/service/ros2_service/{name}/call\x12\xae\x01\n\x07\x44\x65stroy\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\">\x82\xd3\xe4\x93\x02\x38\"6/viamsoleng/api/v1/service/ros2_service/{name}/destroy\x12\xac\x01\n\x06Status\x12\x30.viamlabs.service.ros2_service.v1.ServiceRequest\x1a\x31.viamlabs.service.ros2_service.v1.ServiceResponse\"=\x82\xd3\xe4\x93\x02\x37\"5/viamsoleng/api/v1/service/ros2_service/{name}/statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ros2_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Call']._loaded_options = None
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Call']._serialized_options = b'\202\323\344\223\0025\"3/viamsoleng/api/v1/service/ros2_service/{name}/call'
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Destroy']._loaded_options = None
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Destroy']._serialized_options = b'\202\323\344\223\0028\"6/viamsoleng/api/v1/service/ros2_service/{name}/destroy'
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Status']._loaded_options = None
  _globals['_ROS2SERVICESERVICE'].methods_by_name['Status']._serialized_options = b'\202\323\344\223\0027\"5/viamsoleng/api/v1/service/ros2_service/{name}/status'
  _globals['_SERVICEREQUEST']._serialized_start=92
  _globals['_SERVICEREQUEST']._serialized_end=154
  _globals['_SERVICERESPONSE']._serialized_start=156
  _globals['_SERVICERESPONSE']._serialized_end=201
  _globals['_ROS2SERVICESERVICE']._serialized_start=204
  _globals['_ROS2SERVICESERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
