# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros2_logger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ros2_logger.proto',
  package='viamlabs.service.ros2_logger.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto/ros2_logger.proto\x12\x1fviamlabs.service.ros2_logger.v1\x1a\x1cgoogle/api/annotations.proto\"\x1d\n\x07Request\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"D\n\x08Response\x12\x1b\n\tros_topic\x18\x01 \x01(\tR\x08rosTopic\x12\x1b\n\tlog_level\x18\x02 \x01(\tR\x08logLevel2\xb1\x01\n\x11ROS2LoggerService\x12\x9b\x01\n\x06Status\x12(.viamlabs.service.ros2_logger.v1.Request\x1a).viamlabs.service.ros2_logger.v1.Response\"<\x82\xd3\xe4\x93\x02\x36\"4/viamsoleng/api/v1/service/ros2_logger/{name}/statusb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='viamlabs.service.ros2_logger.v1.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='viamlabs.service.ros2_logger.v1.Request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=119,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='viamlabs.service.ros2_logger.v1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ros_topic', full_name='viamlabs.service.ros2_logger.v1.Response.ros_topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='rosTopic', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='viamlabs.service.ros2_logger.v1.Response.log_level', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='logLevel', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'proto.ros2_logger_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_logger.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'proto.ros2_logger_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_logger.v1.Response)
  })
_sym_db.RegisterMessage(Response)



_ROS2LOGGERSERVICE = _descriptor.ServiceDescriptor(
  name='ROS2LoggerService',
  full_name='viamlabs.service.ros2_logger.v1.ROS2LoggerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=369,
  methods=[
  _descriptor.MethodDescriptor(
    name='Status',
    full_name='viamlabs.service.ros2_logger.v1.ROS2LoggerService.Status',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=b'\202\323\344\223\0026\"4/viamsoleng/api/v1/service/ros2_logger/{name}/status',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROS2LOGGERSERVICE)

DESCRIPTOR.services_by_name['ROS2LoggerService'] = _ROS2LOGGERSERVICE

# @@protoc_insertion_point(module_scope)
