# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros2_action.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ros2_action.proto',
  package='viamlabs.service.ros2_action.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17proto/ros2_action.proto\x12\x1fviamlabs.service.ros2_action.v1\x1a\x1cgoogle/api/annotations.proto\";\n\rActionRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n\x06\x61\x63tion\x18\x02 \x01(\tR\x06\x61\x63tion\",\n\x0e\x41\x63tionResponse\x12\x1a\n\x08response\x18\x01 \x01(\tR\x08response2\xae\x04\n\x11ROS2ActionService\x12\xb2\x01\n\x08SendGoal\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"E\x82\xd3\xe4\x93\x02?\"=/viamsoleng/api/v1/service/ros2_action/{name}/send_goal_async\x12\xb0\x01\n\nCancelGoal\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"A\x82\xd3\xe4\x93\x02;\"9/viamsoleng/api/v1/service/ros2_action/{name}/cancel_goal\x12\xb0\x01\n\nGoalStatus\x12..viamlabs.service.ros2_action.v1.ActionRequest\x1a/.viamlabs.service.ros2_action.v1.ActionResponse\"A\x82\xd3\xe4\x93\x02;\"9/viamsoleng/api/v1/service/ros2_action/{name}/goal_statusb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='viamlabs.service.ros2_action.v1.ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='viamlabs.service.ros2_action.v1.ActionRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='viamlabs.service.ros2_action.v1.ActionRequest.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='action', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=149,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='ActionResponse',
  full_name='viamlabs.service.ros2_action.v1.ActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='viamlabs.service.ros2_action.v1.ActionResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='response', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=195,
)

DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['ActionResponse'] = _ACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'proto.ros2_action_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_action.v1.ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)

ActionResponse = _reflection.GeneratedProtocolMessageType('ActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONRESPONSE,
  '__module__' : 'proto.ros2_action_pb2'
  # @@protoc_insertion_point(class_scope:viamlabs.service.ros2_action.v1.ActionResponse)
  })
_sym_db.RegisterMessage(ActionResponse)



_ROS2ACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ROS2ActionService',
  full_name='viamlabs.service.ros2_action.v1.ROS2ActionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=198,
  serialized_end=756,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendGoal',
    full_name='viamlabs.service.ros2_action.v1.ROS2ActionService.SendGoal',
    index=0,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=b'\202\323\344\223\002?\"=/viamsoleng/api/v1/service/ros2_action/{name}/send_goal_async',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelGoal',
    full_name='viamlabs.service.ros2_action.v1.ROS2ActionService.CancelGoal',
    index=1,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=b'\202\323\344\223\002;\"9/viamsoleng/api/v1/service/ros2_action/{name}/cancel_goal',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GoalStatus',
    full_name='viamlabs.service.ros2_action.v1.ROS2ActionService.GoalStatus',
    index=2,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=b'\202\323\344\223\002;\"9/viamsoleng/api/v1/service/ros2_action/{name}/goal_status',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROS2ACTIONSERVICE)

DESCRIPTOR.services_by_name['ROS2ActionService'] = _ROS2ACTIONSERVICE

# @@protoc_insertion_point(module_scope)
